In [1]:
import pandas as pd
import numpy as np
import os
import sys

project_path = r'C:/Users/palig/MSE/Vertiefungsprojekt1/mse_vp1_rulestimation'

# Add the path to sys.path if it does not already exist
if project_path not in sys.path:
    sys.path.append(project_path)

data_path = os.path.join(project_path, 'data')

df_train = pd.read_csv(os.path.join(data_path, 'kaggle', 'train_data', 'train_data.csv'))
df_test = pd.read_csv(os.path.join(data_path, 'kaggle', 'test_data', 'test_data.csv'))

#Drop empty columns
df_train = df_train.drop(columns=['sensor_24', 'sensor_25', 'sensor_26', 'sensor_27', 'RUL'])
df_test =df_test.drop(columns=['sensor_24', 'sensor_25', 'sensor_26', 'sensor_27'])
columns = df_train.columns

# Original CMAPSS data sets for comparison of statistical values
df1 = pd.read_csv(os.path.join(data_path, 'CMAPSS', 'train_FD001.txt'), delimiter=' ')
df2 = pd.read_csv(os.path.join(data_path, 'CMAPSS', 'train_FD002.txt'), delimiter=' ')
df3 = pd.read_csv(os.path.join(data_path, 'CMAPSS', 'train_FD003.txt'), delimiter=' ')
df4 = pd.read_csv(os.path.join(data_path, 'CMAPSS', 'train_FD004.txt'), delimiter=' ')

df1.columns = columns
df2.columns = columns
df3.columns = columns
df4.columns = columns

def drop_empty(df):
    return df.drop(columns=['sensor_22', 'sensor_23'])

df_train = drop_empty(df_train)
df1 = drop_empty(df1)
df2 = drop_empty(df2)
df3 = drop_empty(df3)
df4 = drop_empty(df4)
df_test = drop_empty(df_test)

In [2]:
import pandas as pd

def compare_statistics(*dataframes):

    means = {}
    stds = {}

    for i, df in enumerate(dataframes, start=1):
        desc = df.describe()
        means[f'df{i}_mean'] = desc.loc['mean']
        stds[f'df{i}_std'] = desc.loc['std']

    comparison_means = pd.DataFrame(means)
    comparison_stds = pd.DataFrame(stds)

    return comparison_means, comparison_stds

# Compare the statistics
comparison_means, comparison_stds = compare_statistics(df1, df2, df3, df4, df_train, df_test)

# Display the results
print("Comparison of mean values:")
display(comparison_means)

print("\nComparison of standard deviations:")
display(comparison_stds)

Comparison of mean values:

,df1_mean,df2_mean,df3_mean,df4_mean,df5_mean,df6_mean
engine_no,51.509016,131.085401,48.633804,124.327194,353.441665,354.311038
time_in_cycles,108.813088,109.156758,139.082649,134.313594,123.331338,95.406589
op_setting_1,-0.000009,23.998203,-0.000024,23.999529,17.211973,17.243810
op_setting_2,0.000002,0.572051,0.000005,0.571343,0.410004,0.410887
op_setting_3,100.000000,94.045909,100.000000,94.031479,95.724344,95.748591
sensor_1,518.670000,472.910644,518.670000,472.882891,485.840890,485.791314
sensor_2,642.680975,579.672852,642.457862,579.420541,597.361022,597.153354
sensor_3,1590.523159,1419.972155,1588.079371,1417.897816,1467.035653,1464.738375
sensor_4,1408.934186,1205.443293,1404.471521,1201.916812,1260.956434,1257.240382
sensor_5,14.620000,8.032034,14.620000,8.031693,9.894999,9.887805
sensor_6,21.609803,11.600813,21.595840,11.589553,14.424935,14.412914
sensor_7,553.367663,282.608423,555.143855,283.331016,359.729968,359.377679
sensor_8,2388.096653,2228.879304,2388.071559,2228.686308,2273.829707,2273.867033
sensor_9,9065.243864,8525.204247,9064.110888,8524.676785,8677.553696,8671.465814
sensor_10,1.300000,1.094963,1.301232,1.096446,1.153705,1.153026
sensor_11,47.541172,42.985190,47.415711,42.874549,44.212049,44.097986
sensor_12,521.413458,266.070579,523.050903,266.737901,338.789821,338.437014
sensor_13,2388.096156,2334.556264,2388.071646,2334.426715,2349.645243,2349.811235
sensor_14,8143.752971,8066.598018,8144.202871,8067.811698,8088.950972,8084.687648
sensor_15,8.442147,9.329653,8.396175,9.285603,9.054747,9.046593
sensor_16,0.030000,0.023326,0.030000,0.023253,0.025185,0.025039
sensor_17,393.210713,348.309777,392.566609,347.760319,360.698801,360.088096
sensor_18,2388.000000,2228.806466,2388.000000,2228.613555,2273.754039,2273.841797
sensor_19,100.000000,97.756796,100.000000,97.751360,98.389146,98.398282
sensor_20,38.816259,20.789409,38.988547,20.864501,25.942709,25.949868
sensor_21,23.289699,12.473491,23.393026,12.519096,15.565700,15.570426

Comparison of standard deviations:

,df1_std,df2_std,df3_std,df4_std,df5_std,df6_std
engine_no,2.922623e+01,74.462440,2.934801e+01,71.994213,205.969348,205.249543
time_in_cycles,6.887857e+01,69.179639,9.884477e+01,89.782506,83.538146,74.311486
op_setting_1,2.187361e-03,14.747437,2.193587e-03,14.780663,16.527988,16.530141
op_setting_2,2.930558e-04,0.310017,2.940381e-04,0.310704,0.367938,0.368078
op_setting_3,0.000000e+00,14.237844,0.000000e+00,14.252050,12.359044,12.328151
sensor_1,6.537152e-11,26.389759,6.684921e-11,26.436807,30.420388,30.426804
sensor_2,5.000295e-01,37.289598,5.230413e-01,37.342758,42.478516,42.430629
sensor_3,6.131295e+00,105.946995,6.810486e+00,106.168038,118.175261,117.856835
sensor_4,9.000636e+00,119.124172,9.773255e+00,119.328023,136.300073,135.728855
sensor_5,3.394700e-12,3.613856,3.602525e-12,3.622863,4.265554,4.265536
sensor_6,1.389018e-03,5.431830,1.811614e-02,5.444009,6.443922,6.443315
sensor_7,8.850867e-01,146.006171,3.437404e+00,146.880224,174.133835,174.056960
sensor_8,7.098674e-02,145.211164,1.582865e-01,145.349414,142.426613,142.135430
sensor_9,2.208302e+01,335.814206,1.998069e+01,336.929194,374.657454,373.202306
sensor_10,4.660829e-13,0.127470,3.484911e-03,0.127681,0.142103,0.142029
sensor_11,2.670934e-01,3.232399,3.000793e-01,3.243514,3.426342,3.408337
sensor_12,7.375693e-01,137.660322,3.255376e+00,138.479134,164.193480,164.110284
sensor_13,7.191870e-02,128.069257,1.581234e-01,128.198723,111.167242,110.890533
sensor_14,1.907660e+01,84.838703,1.650445e+01,85.671238,80.623257,78.956087
sensor_15,3.750562e-02,0.749342,6.051257e-02,0.750380,0.751581,0.748390
sensor_16,1.556432e-14,0.004711,1.750024e-14,0.004685,0.004997,0.005000
sensor_17,1.548778e+00,27.754705,1.761466e+00,27.808418,31.021430,30.932463
sensor_18,0.000000e+00,145.329330,0.000000e+00,145.473663,142.513114,142.218102
sensor_19,0.000000e+00,5.364108,0.000000e+00,5.369460,4.656270,4.644631
sensor_20,1.807428e-01,9.869388,2.488685e-01,9.936391,11.691422,11.701010
sensor_21,1.082498e-01,5.921649,1.492366e-01,5.962694,7.015067,7.020590

In [3]:
import pandas as pd
import numpy as np

# Function for calculating the mean values
def calculate_means(df1, df2):
    combined_data = pd.concat([df1, df2], ignore_index=True)
    feature_columns = [col for col in combined_data.columns if 'sensor' in col or 'op_setting' in col]
    means = combined_data[feature_columns].mean()
    return means.to_dict()

# Calculate mean values for the two groups
mean_group1 = calculate_means(df1, df3)
mean_group2 = calculate_means(df2, df4)

# List of relevant columns


def split_data(df, mean_group1, mean_group2):

    feature_columns = [col for col in df.columns if 'sensor' in col or 'op_setting' in col]
    # Group by `engine_no` and calculate mean values per group
    engine_means = df.groupby('engine_no')[feature_columns].mean()

    # Average values as arrays for distance calculation
    mean_values1 = np.array([mean_group1[sensor] for sensor in feature_columns])
    mean_values2 = np.array([mean_group2[sensor] for sensor in feature_columns])

    tmp = pd.DataFrame()
    # Calculation of distances
    tmp['distance_to_group1'] = np.linalg.norm(engine_means.to_numpy() - mean_values1, axis=1)
    tmp['distance_to_group2'] = np.linalg.norm(engine_means.to_numpy() - mean_values2, axis=1)

    engine_means['distance_to_group1'] = tmp['distance_to_group1']
    engine_means['distance_to_group2'] = tmp['distance_to_group2']

    # Group assignment based on shorter distance
    engine_means['group'] = np.where(
        engine_means['distance_to_group1'] < engine_means['distance_to_group2'], 
        'group1', 
        'group2'
    )

    # Check whether the group assignment has worked
    print(engine_means[['distance_to_group1', 'distance_to_group2', 'group']].head())

    # Add the group assignment to `df`.
    df = df.merge(engine_means[['group']], on='engine_no', how='left')

    # Split the DataFrame according to groups
    if 'group' in df.columns:
        group1_data = df[df['group'] == 'group1']
        group2_data = df[df['group'] == 'group2']
    else:
        raise ValueError("Column 'group' was not created correctly.")

    # Output of the group information
    print(f"Size of Group 1: {group1_data.shape}")
    print(f"Size of Group 2: {group2_data.shape}")

    group1_data = group1_data.drop('group', axis=1)
    group2_data = group2_data.drop('group', axis=1)

    id_group1 = group1_data['engine_no'].unique()
    id_group2 = group2_data['engine_no'].unique()
    

    return group1_data, group2_data, id_group1, id_group2

df_train_13, df_train_24, id_train_13, id_train_24 = split_data(df_train, mean_group1, mean_group2)
df_test_13, df_test_24, id_test_13, id_test_24 = split_data(df_test, mean_group1, mean_group2)

display(df_train_13)

           distance_to_group1  distance_to_group2   group
engine_no
0                  746.621359           13.684499  group2
1                  758.255929           16.156698  group2
2                  723.744890           39.753994  group2
3                  736.541678           21.400615  group2
4                  755.212918           17.384861  group2
Size of Group 1: (45351, 27)
Size of Group 2: (115008, 27)
           distance_to_group1  distance_to_group2   group
engine_no
0                  762.708873           18.007822  group2
1                  734.093393           28.979544  group2
2                  808.794633           59.077577  group2
3                  752.415988           21.275342  group2
4                  720.847780           41.194784  group2
Size of Group 1: (29692, 27)
Size of Group 2: (75205, 27)

,engine_no,time_in_cycles,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
1260,5,1,0.0018,0.0001,100.0,518.67,642.48,1582.06,1409.01,14.62,...,521.64,2388.15,8130.29,8.3813,0.03,393,2388,100.0,38.79,23.3565
1261,5,2,-0.0004,0.0003,100.0,518.67,642.77,1586.79,1403.57,14.62,...,521.59,2388.12,8130.35,8.4391,0.03,392,2388,100.0,39.03,23.4511
1262,5,3,-0.0021,-0.0005,100.0,518.67,642.24,1589.20,1404.16,14.62,...,521.53,2388.06,8134.69,8.4043,0.03,393,2388,100.0,38.74,23.3475
1263,5,4,0.0020,0.0000,100.0,518.67,642.47,1591.55,1401.62,14.62,...,522.23,2388.09,8135.42,8.4220,0.03,390,2388,100.0,38.85,23.1926
1264,5,5,-0.0002,-0.0005,100.0,518.67,642.42,1592.27,1404.57,14.62,...,521.41,2388.12,8135.53,8.4379,0.03,393,2388,100.0,38.88,23.2158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159967,706,271,0.0002,0.0001,100.0,518.67,643.79,1599.14,1431.03,14.62,...,519.85,2388.15,8204.72,8.5201,0.03,398,2388,100.0,38.49,23.0290
159968,706,272,0.0013,0.0002,100.0,518.67,643.44,1602.04,1436.92,14.62,...,519.69,2388.15,8210.46,8.5384,0.03,397,2388,100.0,38.56,23.0985
159969,706,273,0.0014,0.0005,100.0,518.67,643.49,1601.45,1425.42,14.62,...,519.74,2388.20,8215.73,8.4896,0.03,398,2388,100.0,38.37,23.1312
159970,706,274,-0.0017,-0.0002,100.0,518.67,643.53,1598.48,1430.65,14.62,...,519.92,2388.18,8212.77,8.5460,0.03,397,2388,100.0,38.72,23.1060
159971,706,275,-0.0058,0.0001,100.0,518.67,644.09,1600.47,1427.24,14.62,...,519.87,2388.19,8217.25,8.5243,0.03,396,2388,100.0,38.27,23.0597

In [9]:
def normalisation(data_train, data_test):
    # engineID and working time cycle, no need to norm
    prefix_train = data_train.iloc[:, [0, 1]].values
    prefix_test = data_test.iloc[:, [0, 1]].values

    # operational settings and raw sensor data
    inputs_train = data_train.iloc[:, 2:].values
    inputs_test = data_test.iloc[:, 2:].values
    # to avoid devide zero
    eps = 1e-12

    combined = np.concatenate([inputs_train, inputs_test], axis=0)
    min_values = np.min(combined, axis=0)
    max_values = np.max(combined, axis=0)

    normed_data = (inputs_train - min_values) / (max_values - min_values + eps)
    normed_test = (inputs_test - min_values) / (max_values - min_values + eps)

    output_train = np.concatenate((prefix_train, normed_data), axis=1)
    output_test = np.concatenate((prefix_test, normed_test), axis=1)

    return output_train, output_test



df_train_13_normalized, df_test_13_normalized = normalisation(df_train_13, df_test_13)
df_train_24_normalized, df_test_24_normalized = normalisation(df_train_24, df_test_24)

In [5]:
# Save preprocessed data for training
np.savetxt(os.path.join(data_path, 'final', 'train_13.txt'), df_train_13_normalized, fmt="%.6f", delimiter=" ")
np.savetxt(os.path.join(data_path, 'final', 'train_24.txt'), df_train_24_normalized, fmt="%.6f", delimiter=" ")
np.savetxt(os.path.join(data_path, 'final', 'test_13.txt'), df_test_13_normalized, fmt="%.6f", delimiter=" ")
np.savetxt(os.path.join(data_path, 'final', 'test_24.txt'), df_test_24_normalized, fmt="%.6f", delimiter=" ")

In [6]:
# Split the RUL values and save for test data
rul = np.loadtxt(os.path.join(data_path, 'kaggle', 'RUL_test.csv'), delimiter=",", skiprows=1, dtype=np.float32)

rul = rul[:,1]

rul_13 = rul[id_test_13]
rul_24 = rul[id_test_24]

print(rul_13.shape)
print(rul_24.shape)

np.savetxt(os.path.join(data_path, 'final', 'rul_13.txt'), rul_13, fmt='%f')
np.savetxt(os.path.join(data_path, 'final', 'rul_24.txt'), rul_24, fmt='%f')
np.savetxt(os.path.join(data_path, 'final', 'RUL_test.txt'), rul, fmt='%f')

(200,)
(507,)

In [7]:
# Save the ids as well to be able to reassemble them at the end of the test
save_path = os.path.join(data_path, 'final', 'ids.txt')
with open(save_path, 'w') as file:
    file.write("id_train13:\n")
    np.savetxt(file, id_train_13, fmt='%d', newline=' ')
    file.write("\n\nid_train24:\n")
    np.savetxt(file, id_train_24, fmt='%d', newline=' ')
    file.write("\n\nid_test13:\n")
    np.savetxt(file, id_test_13, fmt='%d', newline=' ')
    file.write("\n\nid_test24:\n")
    np.savetxt(file, id_test_24, fmt='%d', newline=' ')